### ISSUE TITLE
not enough balance

### ISSUE THREAD

**Issue by arjun7862** [iotaledger/iota-java#188] opened 2019-07-08 11:31 UTC
hii i have iota balance in my account but show this error please help me 

java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.IllegalStateException: Not enough balance.
        at jota.IotaAPI.getBalanceAndFormat(IotaAPI.java:813)
        at jota.IotaAPI.getInputs(IotaAPI.java:748)
        at jota.IotaAPI.prepareTransfers(IotaAPI.java:667)
        at jota.IotaAPI.sendTransfer(IotaAPI.java:1025)
        at com.example.myapplication.Main2Activity$TaskConnection.prepareTransfer(Main2Activity.java:111)
        at com.example.myapplication.Main2Activity$TaskConnection.doInBackground(Main2Activity.java:77)
        at com.example.myapplication.Main2Activity$TaskConnection.doInBackground(Main2Activity.java:35)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761)

**Comment by kwek20** [comment] 2019-07-10 15:48
Hello @arjun7862 

Are you sure you are using the correct addresses? Iota java checks addresses starting from 0, but stops once it finds an empty address. Could be that your addresses start at index >0?

A good example of sending can be found in our tests:
src/test/java -> org.iota.jota.IotaAPITest#shouldSendTransferWithInputs

Another option is that youre trying to spent funds on the devnet on the mainnet, or vice versa

**Comment by kwek20** [comment] 2019-07-10 16:05
Closed as its a duplicate of #189

**Closed by kwek20** 2019-07-10 16:05 UTC

**Comment by chenlunyusi** [comment] 2020-03-01 03:02
I have the same question. Do you solve it?

**Comment by kwek20** [comment] 2020-03-01 14:55
@chenlunyusi Please see my reply here: https://github.com/iotaledger/iota-java/issues/189#issuecomment-510125367
